from Plane import plane

class requirements:
    def __init__(self, maxLoadFactor, minLoadFactor):
        self.maxLoadFactor = maxLoadFactor #Maximum Ultimate Load Factor
        self.minLoadFactor = minLoadFactor #Minimum Ultimate Load Factor
        self.maxHalfLift = 0 #Lift produced by one side of the wings in the max load factor case[N]
        self.minHalfLift = 0 #Lift produced by one side of the wings in the min load factor case[N]
    
    def setHalfLift(self, plane):
        '''
        Computing Lift required from equilibrium of forces and moments and setting self.maxHalfLift and self.minHalfLift accordingly
        Inputs: object of the type plane
        '''
        x_CoG = plane.x_CoG #Plane Center of Gravity X station
        x_CoP = plane.x_CoP #Plane Center of Pressure X station
        x_Emp = plane.x_Emp #Empennage force X station
        # For max load factor
        maxInertia = - plane.MTOW*9.81*self.maxLoadFactor #Inertia forces
        maxLift = maxInertia * (x_CoG-x_Emp)/(x_Emp-x_CoP) #Total lift via eq of forces and moments
        self.maxHalfLift = maxLift/2 #Lift generated by one wing
        # For min load factor
        minInertia = - plane.MTOW*9.81*self.minLoadFactor #Inertia forces
        minLift = minInertia * (x_CoG-x_Emp)/(x_Emp-x_CoP) #Total lift via eq of forces and moments
        self.minHalfLift = minLift/2 #Lift generated by one wing
